#!/usr/bin/env python3
"""
Generate a sample AI Analyst Weekly report for a given ticker.

Usage:
    python generate_report.py NVDA
    python generate_report.py AAPL 2026-05-11
    python generate_report.py MSFT --output reports/msft.md
"""
import argparse
import asyncio
import sys
from datetime import date
from pathlib import Path


async def run(ticker: str, trade_date: str, output_path: str) -> None:
    from tradingagents.pipeline.runner import run_analysis

    print(f"\n  AI Analyst Weekly — Sample Report Generator")
    print(f"  {'─' * 44}")
    print(f"  Ticker:     {ticker.upper()}")
    print(f"  Date:       {trade_date}")
    print(f"  Analysts:   Fundamental · Technical · Sentiment · News")
    print(f"  Synthesis:  Bull/Bear Debate → Research Manager → Portfolio Manager")
    print()

    agents_done = []

    async def on_agent_complete(agent_name, state):
        agents_done.append(agent_name)
        status = f"  [{len(agents_done)}/8] ✓ {agent_name}"
        summary = state.agent_summaries.get(agent_name, "")
        if summary:
            status += f" — {summary}"
        print(status)

    state = await run_analysis(
        ticker=ticker,
        trade_date=trade_date,
        on_agent_complete=on_agent_complete,
    )

    # ── Build report ──────────────────────────────────────────────────────────

    verdict_line = state.final_decision.split("\n")[0] if state.final_decision else "See below"

    report = f"""# AI Analyst Weekly — {ticker.upper()} Research Report
Generated: {trade_date}

> **Educational research only. Not investment advice.**
> AI Analyst Weekly provides AI-generated analysis for informational purposes.
> Nothing here constitutes a recommendation to buy, sell, or hold any security.
> Always consult a licensed financial advisor before making investment decisions.

---

## Verdict

{state.final_decision if state.final_decision else "Analysis unavailable — check logs."}

---

## Fundamental Analysis

{state.fundamentals_report if state.fundamentals_report else "Unavailable."}

---

## Technical Analysis

{state.market_report if state.market_report else "Unavailable."}

---

## News & Macro

{state.news_report if state.news_report else "Unavailable."}

---

## Sentiment

{state.sentiment_report if state.sentiment_report else "Unavailable."}

---

## Bull vs. Bear Debate

{state.bull_case if state.bull_case else "Unavailable."}

{state.bear_case if state.bear_case else ""}

---

## Research Manager Summary

{state.investment_plan if state.investment_plan else "Unavailable."}

---

## Trader Proposal

{state.trader_proposal if state.trader_proposal else "Unavailable."}

---

*This report was generated by AI Analyst Weekly using 8 specialized AI agents.*
*Not investment advice. AI systems can produce errors. Past analysis accuracy*
*does not predict future results. Not a registered investment adviser.*
"""

    # ── Write output ──────────────────────────────────────────────────────────

    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(report, encoding="utf-8")

    print()
    print(f"  Report saved → {out.resolve()}")
    print()
    print(f"  {verdict_line}")
    print()


def main():
    parser = argparse.ArgumentParser(
        description="Generate an AI Analyst Weekly sample report"
    )
    parser.add_argument("ticker", help="Stock ticker symbol, e.g. NVDA")
    parser.add_argument(
        "trade_date",
        nargs="?",
        default=str(date.today()),
        help="Analysis date YYYY-MM-DD (default: today)",
    )
    parser.add_argument(
        "--output", "-o",
        default=None,
        help="Output file path (default: reports/<TICKER>_<DATE>.md)",
    )
    args = parser.parse_args()

    ticker = args.ticker.upper().strip()
    trade_date = args.trade_date
    output = args.output or f"reports/{ticker}_{trade_date}.md"

    asyncio.run(run(ticker, trade_date, output))


if __name__ == "__main__":
    main()
